import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";

import { Container, Theme, ThemePanel } from "@radix-ui/themes";

import { Outfit } from "next/font/google";
import NavigationBar from "./NavigationBar";

const outfit = Outfit({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme
          appearance="light"
          accentColor="iris"
          panelBackground="solid"
          radius="large"
        >
          <main className={outfit.className}>
            <NavigationBar />
            <Container className="px-2 sm:px-5 md:px-8 lg:px-10 xl:px-12">
              {children}
            </Container>
          </main>
        </Theme>
      </body>
    </html>
  );
}
