import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";

import { Theme, ThemePanel } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme
          appearance="light"
          accentColor="iris"
          panelBackground="solid"
          radius="large"
        >
          <main>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
